# Generated by Django 6.0.4 on 2026-04-21 02:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBotState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='default', max_length=64, unique=True)),
                ('last_update_id', models.BigIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Telegram bot state',
                'verbose_name_plural': 'Telegram bot states',
            },
        ),
        migrations.CreateModel(
            name='TelegramLoginSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('chat_id', models.BigIntegerField(blank=True, null=True)),
                ('telegram_username', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('state', models.CharField(choices=[('NEW', 'New'), ('WAITING_CONTACT', 'Waiting contact'), ('LINKED', 'Linked'), ('ACCESS_SENT', 'Access sent'), ('BLOCKED', 'Blocked'), ('ERROR', 'Error')], default='NEW', max_length=32)),
                ('last_error', models.TextField(blank=True)),
                ('last_interaction_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_login_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-last_interaction_at', '-created_at'),
            },
        ),
    ]
