# Generated by Django 6.0.4 on 2026-04-21 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_telegrambotstate_telegramloginsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramloginsession',
            name='state',
            field=models.CharField(choices=[('NEW', 'New'), ('WAITING_CONTACT', 'Waiting contact'), ('WAITING_USERNAME', 'Waiting username'), ('WAITING_PASSWORD', 'Waiting password'), ('LINKED', 'Linked'), ('ACCESS_SENT', 'Access sent'), ('BLOCKED', 'Blocked'), ('ERROR', 'Error')], default='NEW', max_length=32),
        ),
    ]
