# Generated by Django 6.0.4 on 2026-04-22 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_telegramloginsession_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('DIRECTOR', 'Director'), ('MANAGER', 'Manager'), ('OBSERVER', 'Kuzatuvchi')], default='MANAGER', max_length=20),
        ),
    ]
