# Generated by Django 6.0.4 on 2026-04-22 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesstoken',
            options={'ordering': ('-created_at',), 'verbose_name': 'Kirish tokeni', 'verbose_name_plural': 'Kirish tokenlari'},
        ),
        migrations.AlterModelOptions(
            name='telegramloginsession',
            options={'ordering': ('-last_interaction_at', '-created_at'), 'verbose_name': 'Telegram login sessiyasi', 'verbose_name_plural': 'Telegram login sessiyalari'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Foydalanuvchi', 'verbose_name_plural': 'Foydalanuvchilar'},
        ),
    ]
