# Generated by Django 6.0.4 on 2026-04-21 01:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense'), ('TRANSFER', 'Transfer')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('type', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usd_to_uzs', models.DecimalField(decimal_places=2, max_digits=12)),
                ('effective_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_rates_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-effective_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='ManagerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user__full_name',),
            },
        ),
        migrations.CreateModel(
            name='ManagerTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(choices=[('UZS', 'UZS'), ('USD', 'USD')], max_length=3)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('transfer_kind', models.CharField(choices=[('TRANSFER', 'Transfer'), ('RETURN', 'Return')], default='TRANSFER', max_length=20)),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_transfers_sent', to=settings.AUTH_USER_MODEL)),
                ('to_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='finance.manageraccount')),
            ],
            options={
                'ordering': ('-date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense'), ('TRANSFER', 'Transfer')], max_length=10)),
                ('entry_type', models.CharField(choices=[('COMPANY_INCOME', 'Company income'), ('COMPANY_EXPENSE', 'Company expense'), ('TRANSFER_TO_MANAGER', 'Transfer to manager'), ('MANAGER_EXPENSE', 'Manager expense'), ('MANAGER_RETURN', 'Manager return'), ('MANAGER_TO_MANAGER', 'Manager to manager'), ('ADJUSTMENT', 'Adjustment')], max_length=40)),
                ('wallet_type', models.CharField(choices=[('COMPANY', 'Company'), ('MANAGER', 'Manager')], default='COMPANY', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(choices=[('UZS', 'UZS'), ('USD', 'USD')], max_length=3)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('reference_type', models.CharField(blank=True, max_length=50)),
                ('reference_id', models.CharField(blank=True, max_length=50)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_set', to=settings.AUTH_USER_MODEL)),
                ('manager_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.manageraccount')),
                ('manager_transfer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='finance.managertransfer')),
                ('object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='objects.constructionobject')),
            ],
            options={
                'ordering': ('-date', '-created_at'),
            },
        ),
    ]
