# Generated by Django 6.0.4 on 2026-04-21 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_seed_default_expense_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='entry_type',
            field=models.CharField(choices=[('COMPANY_INCOME', 'Company income'), ('COMPANY_EXPENSE', 'Company expense'), ('TRANSFER_TO_MANAGER', 'Transfer to manager'), ('TRANSFER_TO_OBJECT', 'Transfer to object'), ('MANAGER_EXPENSE', 'Manager expense'), ('OBJECT_EXPENSE', 'Object expense'), ('MANAGER_RETURN', 'Manager return'), ('MANAGER_TO_MANAGER', 'Manager to manager'), ('ADJUSTMENT', 'Adjustment')], max_length=40),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='wallet_type',
            field=models.CharField(choices=[('COMPANY', 'Company'), ('MANAGER', 'Manager'), ('OBJECT', 'Object')], default='COMPANY', max_length=20),
        ),
    ]
