# Generated by Django 6.0.4 on 2026-04-21 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_transaction_entry_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='entry_type',
            field=models.CharField(choices=[('COMPANY_INCOME', 'Company income'), ('COMPANY_EXPENSE', 'Company expense'), ('TRANSFER_TO_MANAGER', 'Transfer to manager'), ('TRANSFER_TO_OBJECT', 'Transfer to object'), ('TRANSFER_FROM_OBJECT', 'Transfer from object'), ('MANAGER_EXPENSE', 'Manager expense'), ('OBJECT_EXPENSE', 'Object expense'), ('MANAGER_RETURN', 'Manager return'), ('MANAGER_TO_MANAGER', 'Manager to manager'), ('ADJUSTMENT', 'Adjustment')], max_length=40),
        ),
    ]
