# Generated by Django 6.0.4 on 2026-04-21 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_seed_default_income_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactioncategory',
            options={'ordering': ('type', 'name'), 'verbose_name': 'Kirim / xarajat turi', 'verbose_name_plural': 'Kirim / xarajat turlari'},
        ),
    ]
