# Generated by Django 6.0.4 on 2026-04-21 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_alter_transactioncategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='managertransfer',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='managertransfer',
            name='target_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='managertransfer',
            name='target_currency',
            field=models.CharField(blank=True, choices=[('UZS', 'UZS'), ('USD', 'USD')], max_length=3),
        ),
        migrations.AddField(
            model_name='transaction',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='target_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='target_currency',
            field=models.CharField(blank=True, choices=[('UZS', 'UZS'), ('USD', 'USD')], max_length=3),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='entry_type',
            field=models.CharField(choices=[('COMPANY_INCOME', 'Ferma kirimi'), ('COMPANY_EXPENSE', 'Ferma chiqimi'), ('TRANSFER_TO_MANAGER', 'Managerga o`tkazma'), ('TRANSFER_TO_OBJECT', 'Obyektga o`tkazma'), ('TRANSFER_FROM_OBJECT', 'Obyektdan qaytarish'), ('MANAGER_EXPENSE', 'Manager xarajati'), ('OBJECT_EXPENSE', 'Obyekt xarajati'), ('MANAGER_RETURN', 'Manager qaytargan pul'), ('MANAGER_TO_MANAGER', 'Managerdan managerga'), ('ADJUSTMENT', 'Tuzatish')], max_length=40),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='wallet_type',
            field=models.CharField(choices=[('COMPANY', 'Ferma'), ('MANAGER', 'Manager'), ('OBJECT', 'Object')], default='COMPANY', max_length=20),
        ),
    ]
