# Generated by Django 6.0.4 on 2026-04-21 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_managertransfer_exchange_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='item_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='transaction',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='raw_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='receipt_file',
            field=models.FileField(blank=True, null=True, upload_to='receipts/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='source',
            field=models.CharField(choices=[('MANUAL', 'Qo`lda'), ('TELEGRAM', 'Telegram'), ('RECEIPT', 'Chek')], default='MANUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='unit',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='transaction',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
    ]
