# Generated by Django 6.0.4 on 2026-04-21 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_transaction_item_name_transaction_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactioncategory',
            name='detail_mode',
            field=models.CharField(choices=[('SIMPLE', 'Oddiy xarajat'), ('MATERIAL', 'Material / miqdorli'), ('FOOD', 'Oziq-ovqat'), ('FUEL', 'Yoqilg`i / texnika')], default='SIMPLE', max_length=20),
        ),
    ]
