# Generated by Django 6.0.4 on 2026-04-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_seed_units_and_expense_items'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangerate',
            options={'ordering': ('-effective_at', '-created_at'), 'verbose_name': 'USD kursi', 'verbose_name_plural': 'USD kurslari'},
        ),
        migrations.AlterModelOptions(
            name='manageraccount',
            options={'ordering': ('user__full_name',), 'verbose_name': 'Manager hisobi', 'verbose_name_plural': 'Manager hisoblari'},
        ),
        migrations.AlterModelOptions(
            name='managertransfer',
            options={'ordering': ('-date', '-created_at'), 'verbose_name': 'Manager o`tkazmasi', 'verbose_name_plural': 'Manager o`tkazmalari'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ('-date', '-created_at'), 'verbose_name': 'Pul harakati', 'verbose_name_plural': 'Pul harakatlari'},
        ),
        migrations.AlterField(
            model_name='managertransfer',
            name='transfer_kind',
            field=models.CharField(choices=[('TRANSFER', 'Pul berish'), ('RETURN', 'Pul qaytarish')], default='TRANSFER', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('INCOME', 'Kirim'), ('EXPENSE', 'Chiqim'), ('TRANSFER', 'Transfer')], max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='wallet_type',
            field=models.CharField(choices=[('COMPANY', 'Ferma'), ('MANAGER', 'Manager'), ('OBJECT', 'Obyekt')], default='COMPANY', max_length=20),
        ),
        migrations.AlterField(
            model_name='transactioncategory',
            name='type',
            field=models.CharField(choices=[('INCOME', 'Kirim'), ('EXPENSE', 'Chiqim'), ('TRANSFER', 'Transfer')], max_length=10),
        ),
    ]
