# Generated by Django 6.0.4 on 2026-04-21 01:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('objects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('role_name', models.CharField(blank=True, max_length=255)),
                ('worker_type', models.CharField(choices=[('monthly', 'Monthly'), ('brigade', 'Brigade')], default='brigade', max_length=20)),
                ('monthly_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('salary_currency', models.CharField(blank=True, choices=[('UZS', 'UZS'), ('USD', 'USD')], max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('full_name',),
            },
        ),
        migrations.CreateModel(
            name='SalaryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(choices=[('UZS', 'UZS'), ('USD', 'USD')], max_length=3)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('description', models.TextField(blank=True)),
                ('source_wallet', models.CharField(choices=[('COMPANY', 'Company'), ('MANAGER', 'Manager')], default='COMPANY', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_payments_created', to=settings.AUTH_USER_MODEL)),
                ('manager_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_payments', to='finance.manageraccount')),
                ('object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_payments', to='objects.constructionobject')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_payments', to='workforce.worker')),
            ],
            options={
                'ordering': ('-date', '-created_at'),
            },
        ),
    ]
