# Generated by Django 6.0.4 on 2026-04-21 12:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarypayment',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
