# Generated by Django 6.0.4 on 2026-04-21 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0003_alter_salarypayment_source_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarypayment',
            name='source_wallet',
            field=models.CharField(choices=[('COMPANY', 'Ferma'), ('MANAGER', 'Manager'), ('OBJECT', 'Object')], default='COMPANY', max_length=20),
        ),
    ]
