# Generated by Django 6.0.4 on 2026-04-22 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0004_alter_salarypayment_source_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarypayment',
            name='receipt_file',
            field=models.FileField(blank=True, null=True, upload_to='salary_receipts/%Y/%m/'),
        ),
    ]
