# Generated by Django 6.0.4 on 2026-04-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0005_salarypayment_receipt_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salarypayment',
            options={'ordering': ('-date', '-created_at'), 'verbose_name': 'Ish haqi to`lovi', 'verbose_name_plural': 'Ish haqi to`lovlari'},
        ),
        migrations.AlterModelOptions(
            name='worker',
            options={'ordering': ('full_name',), 'verbose_name': 'Ishchi', 'verbose_name_plural': 'Ishchilar'},
        ),
        migrations.AlterField(
            model_name='salarypayment',
            name='source_wallet',
            field=models.CharField(choices=[('COMPANY', 'Ferma'), ('MANAGER', 'Manager'), ('OBJECT', 'Obyekt')], default='COMPANY', max_length=20),
        ),
        migrations.AlterField(
            model_name='worker',
            name='worker_type',
            field=models.CharField(choices=[('monthly', 'Oylik ishchi'), ('brigade', 'Brigada')], default='brigade', max_length=20),
        ),
    ]
