# Generated by Django 6.0.4 on 2026-04-22 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ('-created_at',), 'verbose_name': 'Audit log', 'verbose_name_plural': 'Audit loglar'},
        ),
    ]
