# Generated by Django 6.0.4 on 2026-04-21 02:50

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0002_constructionobject_balance_usd_and_more'),
        ('workforce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitem',
            name='assigned_worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_items', to='workforce.worker'),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='agreed_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='currency',
            field=models.CharField(choices=[('UZS', 'UZS'), ('USD', 'USD')], default='UZS', max_length=3),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
