# Generated by Django 6.0.4 on 2026-04-21 12:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0003_workitem_assigned_worker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workitem',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
