# Generated by Django 6.0.4 on 2026-04-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0004_alter_workitem_start_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='constructionobject',
            options={'ordering': ('name',), 'verbose_name': 'Obyekt', 'verbose_name_plural': 'Obyektlar'},
        ),
        migrations.AlterModelOptions(
            name='workitem',
            options={'ordering': ('object__name', 'title'), 'verbose_name': 'Ish turi', 'verbose_name_plural': 'Ish turlari'},
        ),
        migrations.AlterField(
            model_name='constructionobject',
            name='status',
            field=models.CharField(choices=[('active', 'Faol'), ('paused', 'To`xtatilgan'), ('finished', 'Tugallangan')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='status',
            field=models.CharField(choices=[('planned', 'Rejada'), ('in_progress', 'Jarayonda'), ('completed', 'Tugallangan'), ('cancelled', 'Bekor qilingan')], default='planned', max_length=20),
        ),
    ]
